### ISSUE TITLE
数据集连接失效了。。。

### ISSUE THREAD

**Issue by 17764591637** [jzbjyb/DSSA#1]
您好 正在学习您的论文 但是发现数据集连接失效了。。。可以再提供一下吗

**Comment by jzbjyb** [comment]
谢谢反馈，我刚刚更新了README，可以使用google drive的链接下载数据。

**Comment by 17764591637** [comment]
好的 谢谢了！

在 2019-07-31 13:36:30，"jzbjyb" <notifications@github.com> 写道：


谢谢反馈，我刚刚更新了README，可以使用google drive的链接下载数据。
