### ISSUE TITLE
关于训练自己的数据集的输入问题

### ISSUE THREAD

**Issue by 17764591637** [jzbjyb/DSSA#2]
![image](https://user-images.githubusercontent.com/38268685/63482685-5cc07500-c4cc-11e9-89fc-78e8daab322f.png)
其中的w34是怎么计算出来的呢？我用代码输出了train_sample的样例，pair is clueweb09-en0004-07-35706>clueweb09-en0006-75-15933 with weight 1.0，weight的值是用a-NDCG预先计算好的吗

**Comment by jzbjyb** [comment]
w34是这个样本的权重，可以用两个ranking的alpha-nDCG的差值，也可以用uniform的权重都设置成1，具体在文章的4.2.1节有介绍。
